+incdir+../rtl/redundancy_cells/include
+incdir+../rtl/apb/include
+incdir+../rtl/common_cells/include
+incdir+../rtl/cve2/include
+incdir+../rtl/obi/include
+incdir+../rtl/register_interface/include
+define+TARGET_ASIC=1
+define+TARGET_FLIST
+define+TARGET_IHP13
+define+TARGET_RTL
+define+TARGET_SYNTHESIS=1
+define+VERILATOR=1
+define+SYNTHESIS=1
+define+COMMON_CELLS_ASSERTS_OFF=1
../rtl/common_cells/cf_math_pkg.sv
../rtl/redundancy_cells/hsiao_ecc/hsiao_ecc_pkg.sv
../rtl/obi/obi_pkg.sv
../rtl/croc_pkg.sv
../rtl/cve2/cve2_pkg.sv
../rtl/riscv-dbg/dm_pkg.sv
../rtl/apb/apb_pkg.sv
../rtl/common_cells/cdc_reset_ctrlr_pkg.sv
../rtl/soc_ctrl/soc_ctrl_reg_pkg.sv
../rtl/fortalesa/fortalesa_pkg.sv
../rtl/gpio/gpio_reg_pkg.sv
../rtl/obi/relobi_pkg.sv
../rtl/spi/spi_reg_pkg.sv
../rtl/dma/dma_pkg.sv
../rtl/croc_chip.sv
../rtl/redundancy_cells/TMR_voter_fail.sv
../rtl/redundancy_cells/TMR_voter_detect.sv
../rtl/redundancy_cells/TMR_voter.sv
../rtl/fortalesa/acc_mem_intf.sv
../rtl/common_cells/addr_decode.sv
../rtl/common_cells/addr_decode_dync.sv
../rtl/apb_uart/apb_uart.sv
../rtl/redundancy_cells/bitwise_TMR_voter_fail.sv
../rtl/common_cells/cdc_2phase_clearable.sv
../rtl/common_cells/cdc_4phase.sv
../rtl/common_cells/cdc_reset_ctrlr.sv
../rtl/dual_lockstep.sv
../rtl/core_wrap.sv
../rtl/croc_domain.sv
../rtl/croc_soc.sv
../rtl/cve2/cve2_alu.sv
../rtl/cve2/cve2_compressed_decoder.sv
../rtl/cve2/cve2_controller.sv
../rtl/cve2/cve2_core.sv
../rtl/cve2/cve2_counter.sv
../rtl/cve2/cve2_cs_registers.sv
../rtl/cve2/cve2_csr.sv
../rtl/cve2/cve2_decoder.sv
../rtl/cve2/cve2_ex_block.sv
../rtl/cve2/cve2_fetch_fifo.sv
../rtl/cve2/cve2_id_stage.sv
../rtl/cve2/cve2_if_stage.sv
../rtl/cve2/cve2_load_store_unit.sv
../rtl/cve2/cve2_multdiv_fast.sv
../rtl/cve2/cve2_multdiv_slow.sv
../rtl/cve2/cve2_pmp.sv
../rtl/cve2/cve2_prefetch_buffer.sv
../rtl/cve2/cve2_register_file_ff.sv
../rtl/cve2/cve2_wb.sv
../rtl/riscv-dbg/debug_rom/debug_rom.sv
../rtl/riscv-dbg/debug_rom/debug_rom_one_scratch.sv
../rtl/common_cells/delta_counter.sv
../rtl/common_cells/shift_reg.sv
../rtl/common_cells/shift_reg_gated.sv
../rtl/riscv-dbg/dm_csrs.sv
../rtl/riscv-dbg/dm_mem.sv
../rtl/riscv-dbg/dm_obi_top.sv
../rtl/riscv-dbg/dm_sba.sv
../rtl/riscv-dbg/dm_top.sv
../rtl/riscv-dbg/dmi_cdc.sv
../rtl/riscv-dbg/dmi_jtag.sv
../rtl/riscv-dbg/dmi_jtag_tap.sv
../rtl/common_cells/fifo_v3.sv
../rtl/fortalesa/fortalesa_top.sv
../rtl/gpio/gpio.sv
../rtl/gpio/gpio_reg_top.sv
../rtl/redundancy_cells/hsiao_ecc/hsiao_ecc_dec.sv
../rtl/redundancy_cells/hsiao_ecc/hsiao_ecc_enc.sv
../rtl/redundancy_cells/hsiao_ecc/hsiao_ecc_cor.sv
../rtl/redundancy_cells/ecc_wrap/ecc_scrubber.sv
../rtl/redundancy_cells/ecc_wrap/ecc_sram.sv
../rtl/redundancy_cells/ecc_wrap/ecc_sram_port.sv
../rtl/redundancy_cells/ecc_wrap/ecc_sram_dual_port.sv
../rtl/common_cells/lzc.sv
../rtl/obi/obi_intf.sv
../rtl/fortalesa/pe.sv
../rtl/fortalesa/pe_dmr.sv
../rtl/fortalesa/pe_tmr.sv
../rtl/register_interface/periph_to_reg.sv
../rtl/register_interface/lowrisc_opentitan/prim_subreg.sv
../rtl/register_interface/lowrisc_opentitan/prim_subreg_arb.sv
../rtl/register_interface/reg_intf.sv
../rtl/register_interface/reg_to_apb.sv
../rtl/apb_uart/reg_uart_wrap.sv
../rtl/redundancy_cells/rel_fifo.sv
../rtl/redundancy_cells/rel_rr_arb_tree.sv
../rtl/obi/relobi_a_other_decoder.sv
../rtl/obi/relobi_a_other_encoder.sv
../rtl/obi/relobi_decoder.sv
../rtl/obi/relobi_demux.sv
../rtl/obi/relobi_encoder.sv
../rtl/obi/relobi_err_sbr.sv
../rtl/obi/relobi_mux.sv
../rtl/obi/relobi_r_other_decoder.sv
../rtl/obi/relobi_r_other_encoder.sv
../rtl/obi/relobi_tmr_r.sv
../rtl/obi/relobi_xbar.sv
../rtl/obi/relobi_periph_demux.sv
../rtl/obi/obi_sram_shim.sv
../rtl/common_cells/rstgen.sv
../rtl/common_cells/rstgen_bypass.sv
../rtl/apb_uart/slib_clock_div.sv
../rtl/apb_uart/slib_counter.sv
../rtl/apb_uart/slib_edge_detect.sv
../rtl/apb_uart/slib_fifo.sv
../rtl/apb_uart/slib_input_filter.sv
../rtl/apb_uart/slib_input_sync.sv
../rtl/apb_uart/slib_mv_filter.sv
../rtl/soc_ctrl/soc_ctrl_reg_top.sv
../rtl/common_cells/spill_register.sv
../rtl/common_cells/sync.sv
../rtl/fortalesa/syst_array_controller.sv
../rtl/fortalesa/syst_array_top.sv
../rtl/fortalesa/syst_array_v2.sv
../rtl/fortalesa/syst_array_scale_module.sv
../rtl/tech_cells_generic/tc_sram_impl.sv
../ihp13/tc_sram.sv
../ihp13/tc_clk.sv
../rtl/timer_unit/timer_unit.sv
../rtl/timer_unit/timer_unit_counter.sv
../rtl/timer_unit/timer_unit_counter_presc.sv
../rtl/apb_uart/uart_baudgen.sv
../rtl/apb_uart/uart_interrupt.sv
../rtl/apb_uart/uart_receiver.sv
../rtl/apb_uart/uart_transmitter.sv
../rtl/fortalesa/wallace_trunc.sv
../rtl/spi/spi.sv
../rtl/spi/spi_fifo_buffer.sv
../rtl/spi/spi_reg_top.sv
../rtl/dma/dma.sv
../rtl/dma/dma_fifo_buffer.sv
../rtl/dma/dma_interrupt_handler.sv
../rtl/mbist/memory_initializer.sv